force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Follow_up_date__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_date__c</fullName>
    <label>Follow-up date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StaleJobsHelper.cls
public with sharing class StaleJobsHelper {

    public void cleanupStaleJobApplications() {
        // Query jobs that don't have a status of closed or accepted
        List<String> statuses = new List<String>{'Closed', 'Accepted'};
        // Query jobs that have a follow up date 30 days old or more
        Date thirtyDaysOld = Date.today().addDays(-30);
        List<Job_Application__c> jobApps = [SELECT Id, Status__c, Follow_up_date__c, Notes__c
                                            FROM Job_Application__c 
                                            WHERE (Status__c NOT IN :statuses)
                                            AND (Follow_up_date__c <= :thirtyDaysOld)];

        // If no stale jobs, end process
        if (jobApps.isEmpty()) {
            System.debug('No stale jobs to cleanup');
            return;
        }

        // Initialize list and string
        List<Job_Application__c> jobAppsToCleanup = new List<Job_Application__c>();
        String existingNotes = '';

        for (Job_Application__c job : jobApps) {
            job.Status__c = 'Closed';
            // If there are existing notes, add a line break after
            if (job.Notes__c != null) {
                existingNotes = job.Notes__c + '\n\n';
            }
            job.Notes__c = existingNotes + 'Job Application was closed by an automated process on ' + Datetime.now().format();
            jobAppsToCleanup.add(job);
        }
        try {
            update jobAppsToCleanup;
        } catch (Exception e) {
            System.debug('The following exception has occurred: ' + e.getMessage());
        }
    }
}